// <auto-generated />
namespace WebServSendSMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtablelogSend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablelogSend));
        
        string IMigrationMetadata.Id
        {
            get { return "201906060636516_add table logSend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
